descriptions:
  general:
    input: Folder containing input scHi-C contacts in csv format. If 'None' simulated
      scHi-C maps are going to be used.
    output: Output folder for storing simulation results
    n: Number of scHi-C frames to be generated. Only applicable if input==None.
    m: Size of scHi-C frames to be generated (number of beads). Only applicable if
      input==None.
    n_contacts: Number of contacts to be drawn from each in silico structure. Only
      applicable if input==None.
    artificial_structure: 'Index of the in silico structure to be generated as simulation
      input.

      Only applicable if input==None. Available structure indices: 1, 2'
    genome: 'Genome assembly of the input data. Currently supported assemblies: hg19,
      hg38, mm10, GRCm39.'
    chrom: Chromosome to be modeled. The input files are going to be filtered for
      intra-chromosomal contacts within this chromosome.
    pdf_report: Whether to save the simulation diagnostics in a pdf format.
    remove_problematic: A flag indicating whether at each resolution round problematic
      contacts that the simulation was unable to resolve, should be removed.
  simulation:
    platform: 'Available platoforms: CPU, CUDA and OpenCL.'
    resolutions: Resolutions to be used for hierarchical modeling. Expected to be
      in the form of comma separated integer of float numbers in the units of Mb.
    N_steps: Number of simulation steps to take at every resolution
    burnin: Number of simulation steps before starting collecting the simulatin diagnostic
      data
    MC_step: Simulation diagnostic data is going to be collected every MC_step
    sim_step: The simulation step of Langevin integrator
  forcefield:
    ev_formula: 'Type of the Excluded Volume (EV) repulsion. Available types: harmonic'
    ev_min_dist: Excluded Volume (EV) minimal distance
    ev_coef: Excluded Volume (EV) force coefficient
    ev_coef_evol: 'Enable or disable the changing EV coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach ev_coef at the end.

      If False the coefficient will have stable value of ev_coef.'
    bb_formula: 'Type of the Backbone (BB) potential. Available types: harmonic, gaussian'
    bb_opt_dist: Backbone (BB) optimal distance
    bb_lin_thresh: 'Backbone (BB) distance after which the potential grows linearly.

      Must be strictly greater than bb_opt_dist.

      Only applicable if bb_formula is harmonic'
    bb_coef: Backbone (BB) force coefficient
    bb_coef_evol: 'Enable or disable the changing BB coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach bb_coef at the end.

      If False the coefficient will have stable value of bb_coef.'
    sc_formula: 'Type of the Single cell contact (SC) potential. Available types:
      harmonic, gaussian'
    sc_opt_dist: Single cell contact (SC) optimal distance
    sc_lin_thresh: 'Single cell contact (SC) distance after which the potential grows
      linearly.

      Must be strictly greater than sc_opt_dist.

      Only applicable if sc_formula is harmonic'
    sc_coef: Single cell contact (SC) force coefficient
    sc_coef_evol: 'Enable or disable the changing SC coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach sc_coef at the end.

      If False the coefficient will have stable value of sc_coef.'
    ff_formula: 'Type of the Frame force (FF) potential. Available types: harmonic,
      gaussian'
    ff_opt_dist: Frame force (FF) optimal distance
    ff_lin_thresh: 'Frame force (FF) distance after which the potential grows linearly.

      Must be strictly greater than ff_opt_dist.

      Only applicable if ff_formula is harmonic'
    ff_coef: Frame force (FF) force coefficient
    ff_coef_evol: 'Enable or disable the changing FF coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach ff_coef at the end.

      If False the coefficient will have stable value of ff_coef.'
general:
  input: examples/example1_cell_cycle
  output: ./results/tests/teston_off3/
  n: 5
  m: 40
  n_contacts: 50
  artificial_structure: 1
  genome: mm10
  chrom: chr1
  pdf_report: true
  remove_problematic: false
simulation:
  platform: OpenCL
  resolutions: 5,2
  N_steps: 50
  burnin: 0
  MC_step: 1
  sim_step: 20
forcefield:
  ev_formula: harmonic
  ev_min_dist: 1.0
  ev_coef: 100.0
  ev_coef_evol: false
  bb_formula: harmonic
  bb_opt_dist: 1.0
  bb_lin_thresh: 2.0
  bb_coef: 1000.0
  bb_coef_evol: true
  sc_formula: harmonic
  sc_opt_dist: 1.0
  sc_lin_thresh: 2.0
  sc_coef: 10.0
  sc_coef_evol: false
  ff_formula: harmonic
  ff_opt_dist: 1.0
  ff_lin_thresh: 2.0
  ff_coef: 100.0
  ff_coef_evol: false
