descriptions:
  general:
    output: Output folder for storing simulation results
  simulation:
    platform: TODO
    N_steps: TODO
    burnin: TODO
    MC_step: TODO
  forcefield:
    ev_formula: 'Type of the Excluded Volume (EV) repulsion. Available types: TODO'
    ev_min_dist: Excluded Volume (EV) minimal distance
    ev_coef: Excluded Volume (EV) force coefficient
    ev_coef_evol: 'Enable or disable the changing EV coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach ev_coef at the end.

      If False the coefficient will have stable value of ev_coef.'
    bb_formula: 'Type of the Backbone (BB) potential. Available types: TODO'
    bb_opt_dist: Backbone (BB) optimal distance
    bb_lin_thresh: 'Backbone (BB) distance after which the potential grows linearly.

      Must be strictly greater than bb_opt_dist.

      Only applicable if bb_formula is TODO'
    bb_coef: Backbone (BB) force coefficient
    bb_coef_evol: 'Enable or disable the changing BB coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach bb_coef at the end.

      If False the coefficient will have stable value of bb_coef.'
    sc_formula: 'Type of the Single cell contact (SC) potential. Available types:
      TODO'
    sc_opt_dist: Single cell contact (SC) optimal distance
    sc_lin_thresh: 'Single cell contact (SC) distance after which the potential grows
      linearly.

      Must be strictly greater than sc_opt_dist.

      Only applicable if bb_formula is TODO'
    sc_coef: Single cell contact (SC) force coefficient
    sc_coef_evol: 'Enable or disable the changing SC coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach sc_coef at the end.

      If False the coefficient will have stable value of sc_coef.'
    ff_formula: 'Type of the Frame force (FF) potential. Available types: TODO'
    ff_opt_dist: Frame force (FF) optimal distance
    ff_lin_thresh: 'Frame force (FF) distance after which the potential grows linearly.

      Must be strictly greater than ff_opt_dist.

      Only applicable if bb_formula is TODO'
    ff_coef: Frame force (FF) force coefficient
    ff_coef_evol: 'Enable or disable the changing FF coefficient value.

      If True the coefficient will start as 0 at the beginning of the simulation and
      reach ff_coef at the end.

      If False the coefficient will have stable value of ff_coef.'
general:
  output: results2
simulation:
  platform: OpenCL
  N_steps: 100
  burnin: 5
  MC_step: 10
forcefield:
  ev_formula: harmonic
  ev_min_dist: 1.0
  ev_coef: 1000.0
  ev_coef_evol: false
  bb_formula: harmonic
  bb_opt_dist: 1.0
  bb_lin_thresh: 2.0
  bb_coef: 1000.0
  bb_coef_evol: false
  sc_formula: harmonic
  sc_opt_dist: 1.0
  sc_lin_thresh: 2.0
  sc_coef: 1000.0
  sc_coef_evol: false
  ff_formula: harmonic
  ff_opt_dist: 1.0
  ff_lin_thresh: 2.0
  ff_coef: 1000.0
  ff_coef_evol: false
